### PR TITLE
Make rancher support k8s 1.2

### PR DESCRIPTION
**Pull request by antmanler**
* Base forked from [v1.2.0-aphla4](https://github.com/kubernetes/kubernetes/tree/v1.2.0-alpha.4)

* Kubelet will move conatainers to `/docker-deamon`, which will cause rancher cannot monitor the newly created containers after kubelet has been launched

* Reuse rancher's cadvisor (which listen on localhost:9344) when provider is rancher, cadvisor sometime consume lots of resources and there is no reason to deploy two instances on single host

* Additionally there is a [hespter fork](https://github.com/we87/heapster/tree/rancher), it resolves containers' labels and maps rancher's stack to k8s' namespace, service to pod.  It can be deployed using `kubectl create` and it collects and displays rancher's stack containers correctly. 

    check the sreenshot:
    in-heapster
    in-rancher

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
@antmanler This is great work, thanks!  We will need to figure out how to maintain a 1.2 branch of all the rancher k8s projects so that we can continue have 1.1 but then also allow development builds of 1.2.

**Comment by antmanler** [comment]
It seems that k8s is hard to merge without conflicts, I've tried to rebase (also tried merge) the upstream, but got plenty of errors, so I give up and cherry picked change set and forked from 1.2  :(.

I think it's better to make rancher become a standard cloud provider, but the currently problem is how to do custom config on kubelet without patching the cmd.

(What about make a proposal to extend the cloud provider interface to allow a cloud provider modify the kubelet config?)

**Comment by ibuildthecloud** [comment]
@antmanler Again, thanks for the work here.  I've cherry picked all your commits into https://github.com/rancher/kubernetes/tree/rancher-v1.2.0-alpha.8.  Going forward we will create a branch from the upstream tag and then put our patches on it.  For each new tag we will rebase the patches.  Eventually we would like to upstream all of this but currently there is too much we are doing that I don't think is really proper.  For example the networking is a hack.  We are working on a CNI plugin and then when we do that we don't need that hack.

I did have one question about a change you did that I didn't know what was for: https://github.com/we87/kubernetes/commit/6deba6eb42ad85a6514e0a82e3ad3164c3d58175#diff-a9f93108ac59ff44885fc0aea2f29e71R106  The field DockerDaemonContainer doesn't exist anymore and I wasn't sure what that change enabled.

**Comment by antmanler** [comment]
You're welcome, it's my pleasure to have contributions to your great work!

**Pull request closed without merging**
