### PR TITLE
include etc-update-service in the kubeapi-server

### PR DESCRIPTION
**Pull request by wlan0**
@alena1108

### CODE REVIEW

**Comment by wlan0** [comment]
From previous closed PR -  `"Let's not download on start, but in the Dockerfile build instead. Might as well put the migration in a standard location too like /usr/local/bin. Also we need to find an approach that if this service dies it is restarted."`

I don't know how to ensure that this service gets restarted if it dies. @ibuildthecloud @alena1108 

- Should we add this as a sidekick to the existing kube-apiserver and configure healthcheck on that independent container
 - Should we wrap this service and kube-apiserver under a service that responds with state "healthy" only if both api-server and etc-hosts-updater are "healthy"

**Comment by alena1108** [comment]
https://github.com/rancher/rancher/issues/4664
https://github.com/rancher/rancher/issues/4384

**Comment by alena1108** [comment]
@wlan0 as we've decided to go with the sidekick approach for etc/host updater (https://github.com/rancher/rancher-catalog/pull/175/files), should we close this PR?

**Comment by wlan0** [comment]
@alena1108 Yes, we can close this.

**Pull request closed without merging**
