### PR TITLE
WIP: use fqdn instead of hostname

### PR DESCRIPTION
**Pull request by wlan0**
@ibuildthecloud

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Have you determined the impact on https://github.com/rancher/etc-host-updater?

**Comment by wlan0** [comment]
Since etc-host-updater receives the name of the host from rancher, and with the rancher-agent PR for using fqdn instead of hostname, there is no change required in etc-host-updater

**Comment by wlan0** [comment]
Need to resolve this issue before merging this PR - https://github.com/docker/machine/issues/3709

**Comment by alena1108** [comment]
@wlan0 shall we close this one? I see the commit with the same message in k8s 1.4 PR

**Pull request closed without merging**
